-- 테이블 생성
drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity, --null값을 넣었을 때 DB가 알아서 id값을 채워줌
    name varchar(255),
    primary key (id)
);

-- 값 설정
insert into member(name) values('spring')